### ISSUE TITLE
Error pulling v24.7.0 container image using helm chart (Authorization required?)

### ISSUE THREAD

**Issue by drikster80** [Mellanox/network-operator#1052]
**Environment**:
- 4-node GH200 Cluster (Vanilla Kubernetes 1.31)
  - Bluefield-3 DPU in each node & SN3700 Switch (Cumulus Linux)
- GPU Operator Deployed

Attempting to deploy Network Operator v24.7.0 with command:
```
helm show values nvidia/network-operator --version v24.7.0 > values.yaml

# Updated to disable nfd since it was deployed with GPU Operator (`nfd.enabled=false`)

helm install network-operator nvidia/network-operator -n nvidia-network-operator --create-namespace --version v24.7.0 -f ./values.yaml --wait
```

**What happened**:

`ErrImagePull`

Error showing in containerd:
```
Sep 01 18:01:24 gh200-1 containerd[1768487]: time="2024-09-01T18:01:24.687567471Z" level=info msg="PullImage \"nvcr.io/nvstaging/mellanox/network-operator:v24.7.0\""
Sep 01 18:01:25 gh200-1 containerd[1768487]: time="2024-09-01T18:01:25.333471500Z" level=error msg="PullImage \"nvcr.io/nvstaging/mellanox/network-operator:v24.7.0\" failed" error="failed to pull and unpack image \"nvcr.io/nvstaging/mellanox/network-operator:v24.7.0\": failed to resolve reference \"nvcr.io/nvstaging/mellanox/network-operator:v24.7.0\": unexpected status from HEAD request to https://nvcr.io/v2/nvstaging/mellanox/network-operator/manifests/v24.7.0: 401 Unauthorized"
Sep 01 18:01:25 gh200-1 containerd[1768487]: time="2024-09-01T18:01:25.333522412Z" level=info msg="stop pulling image nvcr.io/nvstaging/mellanox/network-operator:v24.7.0: active requests=0, bytes read=1068"
```

**What you expected to happen**:

The images should be pulled without credentials.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Should it be pulling from 'nvstaging'? (`nvcr.io/nvstaging/mellanox/network-operator:v24.7.0`)

Here is the result when attempting to pull with docker (on both nvstaging and nvidia):
```
docker pull nvcr.io/nvstaging/mellanox/network-operator:v24.7.0
Error response from daemon: unauthorized: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>
```

```
docker pull nvcr.io/nvidia/cloud-native/network-operator:v24.7.0
v24.7.0: Pulling from nvidia/cloud-native/network-operator
aa04440524ba: Pull complete
b8e78a3d48f5: Pull complete
836c10435595: Pull complete
4eb1e4c628d6: Pull complete
fc24d032acfc: Pull complete
f4bac45a32a6: Pull complete
ec8d59a67135: Pull complete
Digest: sha256:b8a07696d05fb8e5292991ba731758579313d6983ed3d75dd95e7356024d987c
Status: Downloaded newer image for nvcr.io/nvidia/cloud-native/network-operator:v24.7.0
nvcr.io/nvidia/cloud-native/network-operator:v24.7.0
```

**Logs**:
- Network Operator version: v24.7.0
- Helm Configuration (if applicable):
- Kubernetes' nodes information (labels, annotations and status): `kubectl get node -o yaml`:
[node_logs.txt](https://github.com/user-attachments/files/16830059/node_logs.txt)

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: v1.31.0 Kustomize Version: v5.4.2 Server Version: v1.31.0
- Hardware configuration:
  - Network adapter model and firmware version: Bluefield-3 FW: 32.41.1000
- OS (e.g: `cat /etc/os-release`):  Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): Linux gh200-1 6.5.0-1024-nvidia-64k 25-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 22:12:40 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

- Others:

**Comment by drikster80** [comment]
Locally updating the following line in values.yaml fixed the issue...

```
repository: nvcr.io/nvidia/cloud-native
```

**Comment by rollandf** [comment]
Thanks for reporting.
Working on a fix.

**Comment by rollandf** [comment]
Fixed now also in public repo.

helm fetch https://helm.ngc.nvidia.com/nvidia/charts/network-operator-24.7.0.tgz

**Comment by NordMike** [comment]
I'm trying to run `kubectl apply -f example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml` from the current master and got the same error:
```
Warning  Failed     18s (x3 over 63s)  kubelet            Failed to pull image "nvcr.io/nvstaging/mellanox/doca-driver:25.04-0.0.6.0-0-debian11-amd64": failed to pull and unpack image "nvcr.io/nvstaging/mellanox/doca-driver:25.04-0.0.6.0-0-debian11-amd64": failed to resolve reference "nvcr.io/nvstaging/mellanox/doca-driver:25.04-0.0.6.0-0-debian11-amd64": unexpected status from HEAD request to https://nvcr.io/v2/nvstaging/mellanox/doca-driver/manifests/25.04-0.0.6.0-0-debian11-amd64: 401 Unauthorized
```

Changing `repository: nvcr.io/nvstaging/mellanox` to `repository: nvcr.io/nvidia/cloud-native` as proposed earlier in this issue doesn't help. Error stays the same.

network-operator was installed by instruction in section Deploy Network Operator of `deployment/network-operator/README.md`.

**Comment by noama-nv** [comment]
please use v24.7.1 

here is the CR you looking for matching v24.7.1
https://github.com/Mellanox/network-operator/blob/v24.7.1/example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml

I would advise using recent release v25.1.0 or v24.10.0 

see EOL

https://github.com/Mellanox/network-operator-docs/blob/main/docs/life-cycle-management.rst#network-operator-life-cycle

**Comment by NordMike** [comment]
Thank you for advice. I've tried to use tagged commits. No success yet but error changed.  Now it's "Not found" instead of "Authorization required".

v25.1.0:
```
Warning  Failed     8s (x3 over 52s)   kubelet            Failed to pull image "nvcr.io/nvidia/mellanox/doca-driver:25.01-0.6.0.0-0-debian11-amd64": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/mellanox/doca-driver:25.01-0.6.0.0-0-debian11-amd64": failed to resolve reference "nvcr.io/nvidia/mellanox/doca-driver:25.01-0.6.0.0-0-debian11-amd64": nvcr.io/nvidia/mellanox/doca-driver:25.01-0.6.0.0-0-debian11-amd64: not found
```

v24.10.0:
```
Warning  Failed     27s (x2 over 42s)  kubelet            Failed to pull image "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": failed to resolve reference "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64: not found
```

v24.10.1:
```
Warning  Failed     16s (x2 over 30s)  kubelet            Failed to pull image "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": failed to resolve reference "nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64": nvcr.io/nvidia/mellanox/doca-driver:24.10-0.7.0.0-0-debian11-amd64: not found
```

**Comment by rollandf** [comment]
You can the check the available tags here: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/mellanox/containers/doca-driver/tags

`debian11` is not a supported OS for the DOCA-Driver Container

**Comment by NordMike** [comment]
And it should be the same as the host OS? So I should use https://github.com/Mellanox/doca-driver-build to build my own container for Debian 11 hosts?

**Comment by rollandf** [comment]
Debian was not required before.
Did you consider to install the driver directly on the hosts?
https://developer.nvidia.com/doca-downloads?deployment_platform=Host-Server&deployment_package=DOCA-Host&target_os=Linux&Architecture=x86_64&Profile=doca-ofed&Distribution=Debian

To support Debian in the container, you will need to add a Dockerfile, and fix the entrypoint bash script.

For example, in this PR, SLES support was added:
https://github.com/Mellanox/doca-driver-build/pull/12
