### ISSUE TITLE
v24.7.0 - No arm64 version of sriov-network-operator-config-daemon

### ISSUE THREAD

**Issue by drikster80** [Mellanox/network-operator#1053]
When deploying on GH200 (Grace arm64) servers and enabling the SR-IOV functionality, image `sriov-network-operator-config-daemon:network-operator-24.7.0` does not have a arm64 version available:

**What happened**:
`sriov-network-config-daemon` does not pull

```
sriov-network-config-daemon-5ptkj                         0/1     ErrImagePull 
sriov-network-config-daemon-f2qg8                         0/1     ErrImagePull 
sriov-network-config-daemon-hcm52                         0/1     ErrImagePull 
sriov-network-config-daemon-ztsqw                         0/1     ErrImagePull 
```

When attempting to pull with docker, shows no arm64 version is available. 

```
docker pull nvcr.io/nvidia/cloud-native/sriov-network-operator-config-daemon:network-operator-24.7.0

no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Anything else we need to know?**:
It looks like the upstream sriov-network-operator project merged multi-arch in March in the following PR:
https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/574

**Logs**:
N/A

**Environment**:

Kubernetes version (use kubectl version): Client Version: v1.31.0 Kustomize Version: v5.4.2 Server Version: v1.31.0

Hardware configuration: 
4-node GH200 Cluster (Vanilla Kubernetes 1.31)
Bluefield-3 DPU in each node & SN3700 Switch (Cumulus Linux)
GPU Operator Deployed

Network adapter model and firmware version: Bluefield-3 FW: 32.41.1000
OS (e.g: cat /etc/os-release): Ubuntu 22.04.4 LTS

Kernel (e.g. uname -a): Linux gh200-1 6.5.0-1024-nvidia-64k 25-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 22:12:40 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Comment by e0ne** [comment]
@drikster80  images are re-uploaded. Could you please try again?
