### ISSUE TITLE
VLAN Tagging Support on VF-Attached NICs for Cross-Node Pod Communication

### ISSUE THREAD

**Issue by koh-hr** [Mellanox/network-operator#1111]
Description

I am trying to attach Virtual Functions (VF) to Pods in Kubernetes and enable cross-node communication between these Pods. Specifically, I would like to configure VLAN tagging on the NICs that are recognized within the Pods.

Is it possible to set VLAN tags on the NICs assigned to Pods to allow network isolation and routing via VLANs?

Here is the relevant part of my NicClusterPolicy configuration:
```
apiVersion: v1
items:
- apiVersion: mellanox.com/v1alpha1
  kind: NicClusterPolicy
  ...
    sriovDevicePlugin:
      config: |
        {
          "resourceList": [
            {
              "resourcePrefix": "nvidia.com",
              "resourceName": "hostdev",
              "selectors": {
                "vendors": ["15b3"],
                "devices": ["1014"],
                "drivers": [],
                "pfNames": [],
                "pciAddresses": [],
                "rootDevices": [],
                "linkTypes": [],
                "isRdma": true
              }
            }
          ]
        }
      image: sriov-network-device-plugin
      imagePullSecrets: []
      repository: ghcr.io/k8snetworkplumbingwg
      version: 2cc723dcbc712290055b763dc9d3c090ba41e929
・・・
```
In this setup, we are using SR-IOV and attaching VFs to Pods. However, it is unclear how to configure VLANs on the NICs within the Pods. If this feature is supported, I would appreciate any guidance, documentation, or example configurations to assist in enabling VLAN-tagged communication across nodes.

Thank you in advance for your support!

**Comment by koh-hr** [comment]
@rollandf 
I received help at https://github.com/Mellanox/network-operator/issues/1084.
I'm facing another issue, so I would appreciate any advice you could provide.

**Comment by rollandf** [comment]
You can configure VLAN for VF in the sriov-cni conf:
https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/docs/configuration-reference.md

**Comment by koh-hr** [comment]
@rollandf 
Thank you for the response!

I attempted to use `sriov-cni`, but it seems the plugin isn't present on the node.

- **Event**
  ```plaintext
  Warning  FailedCreatePodSandBox  11s  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "96359e4064451a064032069f8e1331014b53f6d88ea642ad64e8988313ea1ea5": plugin type="multus" name="multus-cni-network" failed (add): [default/sriov-test-worker05/63016b5a-b53e-4ac4-b332-0fec56a627ec:sriov-net]: error adding container to network "sriov-net": failed to find plugin "sriov" in path [/opt/cni/bin /opt/cni/bin]
  ```

- **Node CNI plugins**:
  ```plaintext
  ubuntu@worker05:~$ ls -l /opt/cni/bin
  total 351580
  -rwxr-xr-x 1 root root  4041623 Oct 22 03:04 bandwidth
  -rwxr-xr-x 1 root root  4531309 Oct 22 03:04 bridge
  -rwsr-xr-x 1 root root 62044175 Mar  8  2024 calico
  -rwsr-xr-x 1 root root 62044175 Mar  8  2024 calico-ipam
  -rwxr-xr-x 1 root root 10816051 Oct 22 03:04 dhcp
  -rwxr-xr-x 1 root root  4171248 Oct 22 03:04 dummy
  -rwxr-xr-x 1 root root  4649749 Oct 22 03:04 firewall
  -rwxr-xr-x 1 root root  2491746 Mar  8  2024 flannel
  -rwxr-xr-x 1 root root  4059321 Oct 22 03:04 host-device
  -rwxr-xr-x 1 root root  3521392 Oct 22 03:04 host-local
  -rwsr-xr-x 1 root root 62044175 Mar  8  2024 install
  -rwxr-xr-x 1 root root  4292784 Jun 25 10:31 ipoib
  -rwxr-xr-x 1 root root  4193323 Oct 22 03:04 ipvlan
  -rwxr-xr-x 1 root root  3602373 Oct 22 03:04 loopback
  -rwxr-xr-x 1 root root  4227193 Oct 22 03:04 macvlan
  -rwxr-xr-x 1 root root 42573547 Oct 22 03:04 multus
  -rwxr-xr-x 1 root root  4039793 Oct 22 03:04 portmap
  -rwxr-xr-x 1 root root  4348835 Oct 22 03:04 ptp
  -rwxr-xr-x 1 root root  3716095 Oct 22 03:04 sbr
  -rwxr-xr-x 1 root root  2984504 Oct 22 03:04 static
  -rwxr-xr-x 1 root root  4258344 Oct 22 03:04 tap
  -rwxr-xr-x 1 root root  3603365 Oct 22 03:04 tuning
  -rwxr-xr-x 1 root root  4187498 Oct 22 03:04 vlan
  -rwxr-xr-x 1 root root  3754911 Oct 22 03:04 vrf
  -rwxr-xr-x 1 root root 45764376 Oct 22 03:04 whereabouts
  ```

Is the Network Operator supposed to install the plugin automatically, or does it need to be installed manually?  
The method for manual installation is as follows:

https://github.com/k8snetworkplumbingwg/sriov-cni?tab=readme-ov-file#kubernetes-quick-start
> To deploy SR-IOV CNI by itself on a Kubernetes 1.16+ cluster:
kubectl apply -f images/sriov-cni-daemonset.yaml

--- 

Please let me know if there is anything I missed. Thank you!

**Comment by rollandf** [comment]
NVIDIA Network Operator does not install sriov-cni.
You can install SRIOV Network Operator that will install also sriov-cni or as you mentioned you can do it with the DS you mentioned.

**Comment by koh-hr** [comment]
Thanks to your help, I now understand it better! I’ll try out the suggestion you provided.

**Comment by rollandf** [comment]
Closing this issue as it is not related to Network Operator
