### ISSUE TITLE
Automate Release process

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#131]
**What would you like to be added**:

An automation process to update the needed components when doing a release.

I think we would like to have a `scripts` folder with:

- create-release.sh  : will update charts on master with the release version, create a tag on master, PR then pushed by the user
- update-gh-pages.sh : create helm package from master, and copies the deployment/README.md then updated gh-pages branch, PR then pushed by the user

at a later stage the latter can be used in CI/CD pipeline on tag creation.

**Why is this needed**:

Current release process requires quite a few manual steps.

**Comment by e0ne** [comment]
Automation scripts are implemented
