### ISSUE TITLE
CRDs are not synced 

### ISSUE THREAD

**Issue by e0ne** [Mellanox/network-operator#134]
**What happened**:
CRDs are not synced in these folders:

- https://github.com/Mellanox/network-operator/tree/master/deployment/network-operator/crds
- https://github.com/Mellanox/network-operator/tree/master/config/crd/bases

**What you expected to happen**:
CRDs should be the same for helm chart and manual operator deployment. We should sync them and create some CI checkto not introduce this bug in the future.

**Comment by moshe010** [comment]
It seem partial-closes doesn't works in github. I will reopen this

**Comment by e0ne** [comment]
Partial-closed added because there is no automation for this
