### ISSUE TITLE
MacvlanNetwork should be namespace scoped

### ISSUE THREAD

**Issue by e0ne** [Mellanox/network-operator#139]
**What happened**:
[MacvlanNetwork](https://github.com/Mellanox/network-operator/blob/2bc16f6aca1c4c68cd93dfdec62d02c8f80ea971/api/v1alpha1/macvlannetwork_types.go#L57) is defined as cluster scoped.

**What you expected to happen**:
MacvlanNetwork CRD should be defined with namespace scoped

**Environment**:
- the latest network-operator

**Comment by adrianchiris** [comment]
macvlan network (much like the network types in SR-IOV network operator) has a field which is used to specify the namespace this network applies to (i,e the namespace of the net-attach-def)

Having the CR namespace scope which creates sub-resources in any other namespace does not make sense imo.

Now, we could have omitted the networkNamespace field and make macvlanNetwork CR namespace scoped, then create net-attach-def in the same namespace. However this would not follow the same pattern as sriov-network-operator network CRs..

**Comment by moshe010** [comment]
Ok so let raise it in the next meeting on the sriov network operator.

**Comment by e0ne** [comment]
From one side I agree that using the same approach across different network types in different operators are a good thing to do. It helps users to understand how to use operator faster.

From other side, we already introduced a difference from sriov-networ-operator: SriovNetwork is namespace scoped [1].

> Having the CR namespace scope which creates sub-resources in any other namespace does not make sense imo.

I absolutely agree with you. networkNamespace field always confused me because it creates some resources in  specified namespace for cluster scoped resources. We should have everything in the same namespace specified in a 'namespace' field.


[1] https://github.com/openshift/sriov-network-operator/blob/30c5676a05d6c05fcb66539e76d994f472212c79/config/crd/bases/sriovnetwork.openshift.io_sriovnetworks.yaml#L17

**Comment by adrianchiris** [comment]
This is an API breaking change, but i agree its better to have it namespaced.
