### ISSUE TITLE
Include QoS / DSCP options for RDMA and TCP traffic classes on the NIC

### ISSUE THREAD

**Issue by howels** [Mellanox/network-operator#179]
**What would you like to be added**:

Setting of QoS for RDMA over Ethernet networks, as per the Mellanox documentation:

example:
```
# enable TOS for DSCP & ECN - set DSCP to 40 for RDMA
cma_roce_tos -d mlx5_bond_0 -t 160

# set CNP DSCP priority to 48 for non-RDMA traffic
echo 48 > /sys/class/net/eth0/ecn/roce_np/cnp_dscp
echo 48 > /sys/class/net/eth1/ecn/roce_np/cnp_dscp
```

**Why is this needed**:

To avoid dropping RDMA traffic on Ethernet networks the DSCP tagging system is used to map priorities on classes of traffic. Typically these would need to be run on hosts where RDMA is used, but as the operator is intended to handle RDMA setup for the host it would make sense to delegate this configuration task to the operator I think.

It would not only help to automatically execute these commands but also to centralise the configuration attributes and enable Mellanox best-practice to be easily leveraged.

**Comment by adrianchiris** [comment]
RDMA optimizations span more than TOS and DSCP.
if we decide to tackle it, we need to cover all aspects.

also same thing would need to apply to SR-IOV interfaces as well as physical interface

**Comment by adrianchiris** [comment]
after internal discussions, RDMA configurations and generally nic config should be handled in a separate operator that possibly network operator will deploy.

as the latter component does not (yet) exist closing this one.

**Comment by chewong** [comment]
@adrianchiris is the latter component (an operator to configure RDMA) in the roadmap?

**Comment by adrianchiris** [comment]
yes, first version around april 2024, dates may change.
