### ISSUE TITLE
Is there any plan for adding support to http://github.com/nvidia/gdrcopy?

### ISSUE THREAD

**Issue by MartinForReal** [Mellanox/network-operator#189]
**What would you like to be added**:
http://github.com/nvidia/gdrcopy
**Why is this needed**:
User should load GDR kernel module and I think it is a valid use case to install it using daemonset because it is widely used.

**Comment by moshe010** [comment]
How gdrcopy related to network operator. I am not familiar with this project. Why shouldn't this be added to gpu operator?

**Comment by sakaia** [comment]
for example nv_peer_mem is supported by Mellanox.  https://github.com/Mellanox/nv_peer_memory

Is this clearify the role of network operator and gpu operator?

**Comment by sakaia** [comment]
24h ago the patch for GPUDirect RDMA is added for gpu-operator.
It  should be treated on  GPU-Operator.

Add support for GPUDirect RDMA with GPU Operator
https://github.com/NVIDIA/gpu-operator/commit/24c7bd0d7b32d81dd6507877f49e45b4c04b5fdb

**Comment by moshe010** [comment]
yes, nv peer mem indeed mentioned in mellanox repo, but it is deprecated. The nv peer mem module was rename to nvidia-peer-mem and from cuda r470 it will come in the GPU driver. The support in Network operator is for old cuda driver which we going to deprecated.

**Comment by MartinForReal** [comment]
> How gdrcopy related to network operator. I am not familiar with this project. Why shouldn't this be added to gpu operator?

gdrcopy should be added to GPU operator. Closing the issue. Thanks for reply
