### ISSUE TITLE
Add support for ConnectX-4 Lx

### ISSUE THREAD

**Issue by howels** [Mellanox/network-operator#213]
**What would you like to be added**:

Mellanox ConnectX-4 NICs - specifically the Lx variant.

**Why is this needed**:

We will be deploying this to a large number of systems with existing ConnectX-4 hardware and spoke to the programme team who agreed to add support for this NIC. Please can you officially add support?
Support was initially proposed in https://github.com/Mellanox/network-operator/pull/197 but reverted for some reason.

**Comment by moshe010** [comment]
Hi it should work with connectx 4 and connectx4 lx. We remove it because we don't test it. This is product decision to fucse on new nic. If you have issues with connectx4 you can always open support case and we will help

**Comment by howels** [comment]
> 
> 
> Hi it should work with connectx 4 and connectx4 lx. We remove it because we don't test it. This is product decision to fucse on new nic. If you have issues with connectx4 you can always open support case and we will help

I've reached out to our contact at Mellanox, I have already talked to them and they did agree to support this for 1.0. I'll see when they plan to add ConnectX-4 Lx

**Comment by mkjpryor** [comment]
Big +1 for this. This would make it so much easier to enable RDMA on Kubernetes clusters running on ConnectX-4 hardware.

**Comment by adrianchiris** [comment]
testing wise, network operator is tested on ConnectX5 or newer (we do not intend ATM to test on older hardware).
however there is nothing stopping it from working today on Connectx4.
