### ISSUE TITLE
DCGM exporter crash after deploying the Network operator

### ISSUE THREAD

**Issue by aym-frikha** [Mellanox/network-operator#250]
**What happened**:
When trying to enable the RDMA and get the MOFED operator/pod running, something is changing in the network of the host that make the DCGM exporter crash.

**What you expected to happen**:
I expect the the DCGM stay in a running state
**How to reproduce it (as minimally and precisely as possible)**:
helm install --wait gpu-operator -n gpu-operator --create-namespace -f gpu-operator-values.yaml nvidia/gpu-operator --version v1.8.1

[gpu-operator-config.txt](https://github.com/Mellanox/network-operator/files/7269078/gpu-operator-config.txt)

helm install -n network-operator --create-namespace --wait --version v1.0.0 network-operator mellanox/network-operator
Apply this niccluster

[NicClusterconfig.txt](https://github.com/Mellanox/network-operator/files/7269085/NicClusterconfig.txt)

**Anything else we need to know?**:
ubuntu@hpc-k8s-phy-maas-01:~/deploy/NetworkOperator/examples/rdma/example2$ kubectl logs nvidia-dcgm-exporter-vdb5v -n gpu-operator-resources
time="2021-10-01T16:02:50Z" level=info msg="Starting dcgm-exporter"
time="2021-10-01T16:02:50Z" level=info msg="Attemping to connect to remote hostengine at 10.0.124.84:5555"
time="2021-10-01T16:02:55Z" level=fatal msg="Error connecting to nv-hostengine: Host engine connection invalid/disconnected"

From the host we found tha the hostengine service is working:
ubuntu@hpc-k8s-phy-wrk-g01:~$ ps -aux | grep hostengine
root      584320  0.3  0.0 333332 13756 ?        Ssl  15:34   0:07 /usr/bin/nv-hostengine -n -b 0.0.0.0
ubuntu    653652  0.0  0.0   6436  2620 pts/0    S+   16:08   0:00 grep --color=auto hostengine

**Logs**:
- NicClusterPolicy CR spec and state:
[NicClusterconfig.txt](https://github.com/Mellanox/network-operator/files/7269098/NicClusterconfig.txt)
 
- Output of: `kubectl -n nvidia-network-operator-resources get -A`:
- Network Operator version: 1.0.0
- Logs of Network Operator controller:
[whereabouts-qggtf-whereabouts.txt](https://github.com/Mellanox/network-operator/files/7270337/whereabouts-qggtf-whereabouts.txt)
[whereabouts-4p4sk-whereabouts.txt](https://github.com/Mellanox/network-operator/files/7270338/whereabouts-4p4sk-whereabouts.txt)
[whereabouts-4g2zn-whereabouts.txt](https://github.com/Mellanox/network-operator/files/7270339/whereabouts-4g2zn-whereabouts.txt)
[sriov-device-plugin-qx5fv-kube-sriovdp.txt](https://github.com/Mellanox/network-operator/files/7270340/sriov-device-plugin-qx5fv-kube-sriovdp.txt)
[sriov-device-plugin-9m42z-kube-sriovdp.txt](https://github.com/Mellanox/network-operator/files/7270341/sriov-device-plugin-9m42z-kube-sriovdp.txt)
[rdma-shared-dp-ds-p62qd-rdma-shared-dp.txt](https://github.com/Mellanox/network-operator/files/7270342/rdma-shared-dp-ds-p62qd-rdma-shared-dp.txt)
[rdma-shared-dp-ds-86frs-rdma-shared-dp.txt](https://github.com/Mellanox/network-operator/files/7270344/rdma-shared-dp-ds-86frs-rdma-shared-dp.txt)
[mofed-ubuntu20.04-ds-mn8fb-mofed-container.txt](https://github.com/Mellanox/network-operator/files/7270345/mofed-ubuntu20.04-ds-mn8fb-mofed-container.txt)
[mofed-ubuntu20.04-ds-jtxxb-mofed-container.txt](https://github.com/Mellanox/network-operator/files/7270346/mofed-ubuntu20.04-ds-jtxxb-mofed-container.txt)
[kube-multus-ds-bdwlt-kube-multus.txt](https://github.com/Mellanox/network-operator/files/7270347/kube-multus-ds-bdwlt-kube-multus.txt)
[kube-multus-ds-7wfrz-kube-multus.txt](https://github.com/Mellanox/network-operator/files/7270348/kube-multus-ds-7wfrz-kube-multus.txt)
[kube-multus-ds-567p2-kube-multus.txt](https://github.com/Mellanox/network-operator/files/7270349/kube-multus-ds-567p2-kube-multus.txt)
[network-operator-node-feature-discovery-worker-mtjfb-worker.txt](https://github.com/Mellanox/network-operator/files/7270350/network-operator-node-feature-discovery-worker-mtjfb-worker.txt)
[network-operator-node-feature-discovery-worker-jw6vq-worker.txt](https://github.com/Mellanox/network-operator/files/7270351/network-operator-node-feature-discovery-worker-jw6vq-worker.txt)
[network-operator-node-feature-discovery-worker-2jxlw-worker.txt](https://github.com/Mellanox/network-operator/files/7270352/network-operator-node-feature-discovery-worker-2jxlw-worker.txt)
[network-operator-node-feature-discovery-worker-2hr8q-worker.txt](https://github.com/Mellanox/network-operator/files/7270353/network-operator-node-feature-discovery-worker-2hr8q-worker.txt)
[network-operator-node-feature-discovery-master-596fb8b7cb-4hdh2-master.txt](https://github.com/Mellanox/network-operator/files/7270354/network-operator-node-feature-discovery-master-596fb8b7cb-4hdh2-master.txt)
[network-operator-547cb8d999-fbtg8-network-operator.txt](https://github.com/Mellanox/network-operator/files/7270355/network-operator-547cb8d999-fbtg8-network-operator.txt)

- Logs of the various Pods in `nvidia-network-operator-resources` namespace:
- Helm Configuration (if applicable):
- Kubernetes' nodes information (labels, annotations and status): `kubectl get node -o yaml`:
-
[kubectl get node.txt](https://github.com/Mellanox/network-operator/files/7270360/kubectl.get.node.txt)
 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21

- Hardware configuration: DGX2 server
  - Network adapter model and firmware version: Mellanox Technologies MT28908 Family [ConnectX-6] 
                         [PN] Part number: MC
                        [EC] Engineering changes: AC
                        [V2] Vendor specific: MCX653105A-HDAT
                        [SN] Serial number: MT2043T04073
- OS (e.g: `cat /etc/os-release`): ubuntu focal
- Kernel (e.g. `uname -a`): Linux  5.4.0-86-generic 97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by e0ne** [comment]
@aym-frikha did you try to not deploy MOFED using Network Operator? AFAIK, MOFED is pre-installed on DGX

**Comment by moshe010** [comment]
we have DGX helm values example https://github.com/Mellanox/network-operator/blob/master/example/dgx-helm-values.yaml  for this case.

**Comment by aym-frikha** [comment]
Hi, I'm using ubuntu 20.04, it's not DGX-OS, so MOFED is not pre-installed here.

**Comment by moshe010** [comment]
@aym-frikha what kind of network  DCGM exporter is using? (host network/mellanox interface)?
when we load the mofed container it recreate the net devices so if for example DCGM exporter uses host network or Mellanox interface and ofed is recreating the netdevice . 
Also if DCGM exporter crash k8s should restart it and than it should work. Isn't that the case?

**Comment by e0ne** [comment]
@aym-frikha it will be fixed in GPU Operator v1.9.0
