### ISSUE TITLE
can we set DSCP on VF

### ISSUE THREAD

**Issue by davidstack** [Mellanox/network-operator#269]
i use SRIOV to get roce vf,,we can set dscp on PF with this command
`
mlnx_qos –i ens12f1 –trust=dscp
mlnx_qos –i ens12f1 –pfc=0,0,0,1,0,0,0,0
echo 106> /sys/class/infiniband/mlx5_0/tc/1/traffic_class
echo 1> /sys/class/net/ ens12f1/ecn/roce_np/enable/3
echo 1> /sys/class/net/ ens12f1/ecn/roce_rp/enable/3
echo 48> /sys/class/net/ ens12f1/ecn/roce_np/cnp_dscp

`

is there any metho to set dscp for VF?
**What would you like to be added**:

**Why is this needed**:

**Comment by moshe010** [comment]
Hello, the request is to allow configure dscp when using sriov cni?

**Comment by davidstack** [comment]
@moshe010 yes

**Comment by moshe010** [comment]
Did you try same command with VF netdevice?

**Comment by davidstack** [comment]
these command can not run in container，‘no permission to modify’

**Comment by moshe010** [comment]
I meant can you run it on the host?

**Comment by davidstack** [comment]
yes

**Comment by moshe010** [comment]
so you need  to add it to sriov-cni first
