### ISSUE TITLE
Best practice for post-MOFED-pod device configuration?

### ISSUE THREAD

**Issue by esigler** [Mellanox/network-operator#303]
In our current host-based MOFED installation, we have a post-install step that renames our IB devices.  Switching to Network Operator, I've come up with a few different hacky workarounds for waiting for the MOFED pod to be ready.  It would be useful to have a hook of some kind in Network Operator, where I could add a stage after the MOFED Pod.  Would a pull request like that be considered?

**Comment by adrianchiris** [comment]
Hey,
Have you considered using udev rules to rename your device ?

**Comment by adrianchiris** [comment]
closing this one due to inactivity. please re-open if deemed necessary.
