### ISSUE TITLE
dont use scheduler.alpha.kubernetes.io annotation

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#304]
**What happened**:

scheduler.alpha.kubernetes.io is deprecated in k8s v1.16+. this emits a warning when deploying components which have this annotation

```
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
```

**What you expected to happen**:

No warning to be emitted, need to use `priorityClassName` instead

**Comment by rollandf** [comment]
@adrianchiris can we close this issue?

**Comment by adrianchiris** [comment]
Done. thx for working on it
