### ISSUE TITLE
nvidia-network-operator-resources namespace is not created automatically

### ISSUE THREAD

**Issue by kwozyman** [Mellanox/network-operator#308]
**What happened**:

> WARN	controllers.NicClusterPolicy	Error occurred while syncing states	{"nicclusterpolicy": "/nic-cluster-policy", "error:": "failed to create/update objects: namespaces \"nvidia-network-operator-resources\" not found", "error:Verbose": "namespaces \"nvidia-network-operator-resources\" not found\nfailed to create/update objects\ngithub.com/Mellanox/network-operator/pkg/state.(*stateOFED).Sync\n\t/workspace/pkg/state/state_ofed.go:119\ngithub.com/Mellanox/network-operator/pkg/sta...

In the manager logs after applying a simple ClusterNicPolicy.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy operator and apply ClusterNicPolicy.

**Anything else we need to know?**:

After manually creating the `nvidia-network-operator-resources` namespace, the deployment continues.

**Environment**:

```
$ oc version
Client Version: 4.9.4
Server Version: 4.9.9
Kubernetes Version: v1.22.3+4dd1b5a
```

**Comment by adrianchiris** [comment]
Seems like the namespace resource is not created when installing using operator bundle. i see its missing from the bundle

**Comment by adrianchiris** [comment]
cc @rollandf

**Comment by adrianchiris** [comment]
with #321 merged network-operator now deploy its related k8s resources in its own namespace (no need for an additional namesapce) so creation of the additional namespace is no longer required.
