### ISSUE TITLE
[bug] rdma shared dp container fails with "non-Rdma Device" after reboot

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#31]
after deploying the nic operator with rdma-shared device plugin ,ofed driver, and nv_peer_mem, and successfully creating traffic. if the machine is rebooted, the rdma shared device plugin container may fail because it starts before the ofed driver container is finished loading the modules and causing the rdma shared device plugin to complain in the logs (the container finishes its work and it will be in ready state) with "non-Rdma Device <interace name>".

Workaround: restart rdma shared device plugin containers

**Comment by adrianchiris** [comment]
@Mmduh-483 can this be closed ?  this is addressed by https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/pull/26

**Comment by Mmduh-483** [comment]
@adrianchiris I think it should be should be solved now, but let @AbdYsn verify it on real setup
