### ISSUE TITLE
specify nodeAffinity in values.yaml seems not working when trying deploy multus on master node

### ISSUE THREAD

**Issue by libzhang** [Mellanox/network-operator#310]
**What happened**:
for a previous issue https://github.com/Mellanox/network-operator/issues/264,  it is targeted resolved in 1.1.0 by https://github.com/Mellanox/network-operator/pull/248,  and now I tried 1.1.0,  I specified nodeAffinity in values.yaml when installing with helm.  but multus is still not deployed to master node.  
or could you give an example on how to make the nodeAffinity work?   

**What you expected to happen**:
multus can be deployed on master node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Logs**:
- NicClusterPolicy CR spec and state:
```
~> kubectl get nicclusterpolicy -o yaml
apiVersion: v1
items:
- apiVersion: mellanox.com/v1alpha1
  kind: NicClusterPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: network-operator
      meta.helm.sh/release-namespace: network-operator
    creationTimestamp: "2022-02-22T09:14:49Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: nic-cluster-policy
    resourceVersion: "63507712"
    uid: 574d5f65-285f-4f98-b0f5-f16fdc664e17
  spec:
    psp:
      enabled: false
    rdmaSharedDevicePlugin:
      config: |
        {
          "configList": [
            {
              "resourceName": "rdma_shared_device_a",
              "rdmaHcaMax": 1000,
              "selectors": {
                "vendors": [],
                "deviceIDs": [],
                "drivers": [],
                "ifNames": ["pslave-0"],
                "linkTypes": []
              }
            }
          ]
        }
      image: k8s-rdma-shared-dev-plugin
      repository: nvcr.io/nvidia/cloud-native
      version: v1.2.1
    secondaryNetwork:
      cniPlugins:
        image: plugins
        repository: ghcr.io/k8snetworkplumbingwg
        version: v0.8.7-amd64
      ipamPlugin:
        image: whereabouts
        repository: ghcr.io/k8snetworkplumbingwg
        version: v0.4.2-amd64
      multus:
        image: multus-cni
        repository: ghcr.io/k8snetworkplumbingwg
        version: v3.8
  status:
    appliedStates:
    - name: state-pod-security-policy
      state: ignore
    - name: state-whereabouts-cni
      state: ready
    - name: state-multus-cni
      state: ready
    - name: stage-container-networking-plugins
      state: ready
    - name: state-OFED
      state: ignore
    - name: state-SRIOV-device-plugin
      state: ignore
    - name: state-RDMA-device-plugin
      state: ready
    - name: state-NV-Peer
      state: ignore
    state: ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
- Output of: `kubectl -n nvidia-network-operator-resources get -A`:
- Network Operator version:  1.1.0
- Logs of Network Operator controller:
- Logs of the various Pods in `nvidia-network-operator-resources` namespace:
- Helm Configuration (if applicable):
- Kubernetes' nodes information (labels, annotations and status): `kubectl get node -o yaml`:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Hardware configuration:
  - Network adapter model and firmware version:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by libzhang** [comment]
I suspect that this file also may need to update to make it work ? can you confirm ?

**Comment by libzhang** [comment]
fyi,  I manually edit the nicclusterpolicy and added the nodeAffinity,  multus is deployed on master now.  so it should be an issue in the chart template above that can not pass the nodeAffinity to nicclusterpolicy. 
any workaround or we need to fix this ? 
```
  spec:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
    psp:
      enabled: false
    rdmaSharedDevicePlugin:
```

**Comment by adrianchiris** [comment]
PR#349 addressed the issue
