### ISSUE TITLE
[bug] modules are not cleaned on delete node

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#32]
If a node is deleted from a cluster using kubectl delete nodes, and if the ofed driver container was deployed on that node. The containers of the ofed drivers will be deleted, but the ofed modules will not be unloaded. and to unload them, the ofed should be installed, or the ofed driver container should be deployed.

**Comment by e0ne** [comment]
It's fixed by https://github.com/Mellanox/network-operator/commit/1d7ea37df09acdd04e9226ad121ec21e53718046
