### ISSUE TITLE
Update  k8s-rdma-shared-dev-plugin to avoid available resources=0 when Kubelet restarted

### ISSUE THREAD

**Issue by howels** [Mellanox/network-operator#322]
Fix is included in: https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/pull/46

Needed for Production usage of RDMA, where Nodes was be restarted.

Please update [k8s-rdma-shared-dev-plugin](https://github.com/Mellanox/k8s-rdma-shared-dev-plugin) component.

**Comment by adrianchiris** [comment]
network-operator deploys latest version (v1.3.2) of rdma shared device plugin. closing this one.
