### ISSUE TITLE
Bump versions

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#370]
We should keep network-operator updated with latest components

- [x] go 1.18
- [x] operator sdk
- [x] golangci-lint
- [x] hadolint
- [x] helm
- [x] kubernetes libs
- [x] controller runtime libs
- [x] Dockerfile to build with go 1.18

**Comment by adrianchiris** [comment]
#371

**Comment by e0ne** [comment]
Already implemented
