### ISSUE TITLE
A100 and H100 chips not mentioned in the README

### ISSUE THREAD

**Issue by elgalu** [Mellanox/network-operator#391]
https://github.com/Mellanox/network-operator/blob/c8412593ea36e8c12664036ed6c6d171a17310a4/README.md?plain=1#L298
A100 and H100 chips are not mentioned in the README, are they supported?

**Comment by e0ne** [comment]
@elgalu thanks for raising this topic. We need to update a list with A100 as a supported GPU. H100 isn't tested yet

**Comment by adrianchiris** [comment]
We dont maintain the list of supported GPUs in this README. these GPUs are given as examples.
GPUs and their model have no real effect on this project and are more relevant to [GPU Operator](https://github.com/NVIDIA/gpu-operator/tree/master/deployments/gpu-operator)

@e0ne IMO we should close this one.
