### ISSUE TITLE
node-feature-discovery found in Chart.yaml, but missing in charts/ directory

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [Mellanox/network-operator#398]
**What happened**:
When I deploy network-operator by follow command:
helm install -n network-operator --create-namespace network-operator deployment/network-operator --kubeconfig=/root/.kube/xxx.config
then it reports Error: INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: node-feature-discovery

Reason:
in deployment/network-operator/Chart.yaml, it contains node-feature-discovery dependency, but in deployment/network-operator/charts/, it does not contain node-feature-discovery.

**Comment by e0ne** [comment]
@wangxiaoyang-dev  you need to download dependency manually. Please, follow [helm documentation ](https://helm.sh/docs/helm/helm_dependency_update/)for it.

**Comment by wangxiaoyang-dev** [comment]
@e0ne thx
