### ISSUE TITLE
Failed to watch *v1beta1.PodSecurityPolicy: unknown (get podsecuritypolicies.policy)

### ISSUE THREAD

**Issue by yanchaocc** [Mellanox/network-operator#400]
E0814 10:50:16.935263       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PodSecurityPolicy: unknown (get podsecuritypolicies.policy)

my network-operator deoloyment with logs as above. Any Idea?

version: network-operator-1.2.0
k8s : v1.19
node os : centos 7

![image](https://user-images.githubusercontent.com/17809819/184533505-22b8c167-037c-4191-8dc6-8ee9c7bfd460.png)

**Comment by mkjpryor** [comment]
UPDATE

This looks like it is going to be fixed in the next version. Hopefully it will be released soon!!

**Comment by rollandf** [comment]
Hey @mkjpryor, it should be fixed in #406 .
Can we close this one?

**Comment by mkjpryor** [comment]
This is fixed in the latest release, so feel free to close.
