### ISSUE TITLE
Nodes with GPU taints are not tolerated by Network Operator pods

### ISSUE THREAD

**Issue by tariq1890** [Mellanox/network-operator#435]
**What happened**:

We are trying to provision Network Operator components onto a HPC Node with GPU and Mellanox CX-5 NICs in a Managed Cluster in OCI. The Nodes have the `nvidia.com/gpu NoSchedule` taints, so we don't have the required components scheduled onto them

i) cni-plugins
ii) multus CNI
iii) whereabouts CNI

**What you expected to happen**:
The above components should have tolerated the GPU nodes

**How to reproduce it (as minimally and precisely as possible)**:
i) Provision a K8s cluster whose nodes have the `nvidia.com/GPU` taint
ii) Run helm install of the network operator chart
**Anything else we need to know?**:

**Logs**:
- NicClusterPolicy CR spec and state:
- Output of: `kubectl -n nvidia-network-operator get -A`:
- Network Operator version:
- Logs of Network Operator controller:
- Logs of the various Pods in `nvidia-network-operator` namespace:
- Helm Configuration (if applicable):
- Kubernetes' nodes information (labels, annotations and status): `kubectl get node -o yaml`:

**Environment**:
- Hardware configuration:
  - Network adapter model and firmware version: MLNX_OFED_LINUX-5.4-3.4.0.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): `Linux inst-2z6qj-osakardma-np-bm-custom 5.15.0-1021-oracle #27~20.04.1-Ubuntu SMP Mon Oct 17 01:55:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Others:

**Comment by adrianchiris** [comment]
So the ask here is to support providing additional tolerations for Network-Operator (workload) operands.

This should be regarded as an enhancement.

**Comment by e0ne** [comment]
Related PR: #431

**Comment by rollandf** [comment]
@tariq1890 @e0ne 
can we close this one?

**Comment by tariq1890** [comment]
Hi @rollandf I don't think that PR fully resolves this issue. The different operands in Network-operator would need the `nvidia.com/gpu` taint tolerations added to them or at least have the option to configure custom tolerations

**Comment by tariq1890** [comment]
Sure, Approach 1. works for me

**Comment by tariq1890** [comment]
Actually with #489, I think this can be closed
