### ISSUE TITLE
Makefile targets should use pre-defined versions of controller-gen/operator-sdk 

### ISSUE THREAD

**Issue by e0ne** [Mellanox/network-operator#444]
**What happened**: each time new controller-gen/operator-sdk  are downloaded which introduces unexpected changes to CRDs

**What you expected to happen**: Makefile targets use pinned version of controller-gen/operator-sdk  to get consistent result

**Comment by adrianchiris** [comment]
we should suffix these downloaded binaries with version so that when bumped, it will download and execute the new one.
