### ISSUE TITLE
nodeSelector of sriov-network-operator components are hard-coded and not configurable

### ISSUE THREAD

**Issue by tariq1890** [Mellanox/network-operator#469]
**What would you like to be added**:

We would like to be able to configure the nodeSelector of `sriov-network-operator`

**Why is this needed**:

We provision managed clusters with different node roles and different naming conventions for plain nodes and nodes with sriov-enabled mlnx devices.  We would like to be able to specify the custom node roles for the sriov-cni and sriov-device-plugin 

For more details, please see [here](https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/417)

**Comment by e0ne** [comment]
@tariq1890  it's supported in helm values: https://github.com/Mellanox/network-operator/blob/83c9db2053453c7b8e24559ee7b45c478ce6ed18/deployment/network-operator/values.yaml#L71

**Comment by tariq1890** [comment]
@e0ne The issue was meant for the components that `sriov-network-operator` namely `sriov-cni` and `sriov-device-plugin`

**Comment by e0ne** [comment]
> @e0ne The issue was meant for the components that `sriov-network-operator` namely `sriov-cni` and `sriov-device-plugin`

It's configured by `configDaemonNodeSelector` field in `SriovOperatorConfig` object. If it doesn't feet your needs, please file a bug to https://github.com/k8snetworkplumbingwg/sriov-network-operator/pulls

**Comment by e0ne** [comment]
Fixed by #479
