### ISSUE TITLE
Remove wildcard usage in kube builder annotations

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#595]
we got wildcards set in the following reconcilers:

https://github.com/Mellanox/network-operator/blob/84f986f33d0753e8dacfe946bca05bd994f85fe9/controllers/ipoibnetwork_controller.go#L53
https://github.com/Mellanox/network-operator/blob/84f986f33d0753e8dacfe946bca05bd994f85fe9/controllers/macvlannetwork_controller.go#L55
https://github.com/Mellanox/network-operator/blob/84f986f33d0753e8dacfe946bca05bd994f85fe9/controllers/nicclusterpolicy_controller.go#L58

hostdevice controller seems to be the only saint who doesnt use wildecards :)  

we should use explicit resources for better security.

From looking over, it seems safe to me to remove the relevant lines from macvlan and ipoib reconcilers
in nicclusterpolicy reconciler we should set nicclusterpolicies resource explicitly.

**Comment by rollandf** [comment]
Helm template for role should be aligned the same

**Comment by rollandf** [comment]
FIxed in #605
