### ISSUE TITLE
Network operator fails to delete after deploying secondary network multus

### ISSUE THREAD

**Issue by Mmduh-483** [Mellanox/network-operator#74]
When deploying Multus secondary network, it generates config file `00-multus.conf` which will be CNI config file, when Multus has removed the config file and bin file will stay which leading to use Multus even if the secondary network was deleted.

When Muluts is deleted also the permission will be deleted, thus lead to failure in creating/removing any pod that uses CNI including removing the network operator itself.

https://github.com/intel/multus-cni/pull/593 fixes the issue in Multus

**Comment by adrianchiris** [comment]
So, for the time being we should avoid undeploying multus if its deployed by the operator until issue is fixed in multus.

**Comment by adrianchiris** [comment]
As a WA we have downgraded multus cni version to `v3.4.1` this issue should be handled upstream as its a degradation of functionality
