### ISSUE TITLE
The operator's binary file should contain information about version of the build and print it on start

### ISSUE THREAD

**Issue by ykulazhenkov** [Mellanox/network-operator#744]
**What would you like to be added**:
The binary should contain and print information about build/release, e.g. version, date, commit

**Why is this needed**:
To simplify debugging

**Comment by killianmuldoon** [comment]
I think Kubernetes has a good version of this - taken directly from git and compiled into the code via ldflags - https://github.com/kubernetes/kubernetes/blob/ec71e53adb6dc9f1af3662448f483f3f15971b6b/hack/lib/version.sh#L147-L185

We could simplify it a bit and just call it directly from the Makefile. Does that make sense @ykulazhenkov ?

**Comment by killianmuldoon** [comment]
Will solve this as part of #742

**Comment by ykulazhenkov** [comment]
@killianmuldoon  Thanks!

fixed in https://github.com/Mellanox/network-operator/pull/746
