### ISSUE TITLE
[Enhancement] A way to inject relatedImages to OLM ClusterServiceVersion obj (operator bundle)

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/network-operator#765]
Currently we manually add relatedImages to CSV (ClusterServiceVersion) obj, we would like to have a way where these are added when running make bundle cmd for a specific release.

see: https://github.com/Mellanox/network-operator/pull/760/files/0f3d453cbbbcf1855a9332c2f626efd433727963#r1455212805

**Comment by rollandf** [comment]
Done in #987
