### ISSUE TITLE
Cannot add tolerations without using all of the key, value, and effect values

### ISSUE THREAD

**Issue by OguzPastirmaci** [Mellanox/network-operator#812]
With 23.7.0 and 23.10.0, it's not possible to add a toleration to the manifests to tolerate all taints, because the operator expects to have all three fields (key, value, effect) defined.

Toleration we want to use:

```
tolerations:
- operator: "Exists"
```

**Comment by ykulazhenkov** [comment]
Hi @OguzPastirmaci which tolerations are you referring to? For DaemonSets?

There is a bug with DaemoSet tolerations at the moment, should be fixed by https://github.com/Mellanox/network-operator/pull/813.

I tested this toleration after the fix and it was set correctly.

**Comment by OguzPastirmaci** [comment]
@ykulazhenkov, yes the Daemonsets, but it's fixed with @jessicaxiejw's PR. Thanks!
