### ISSUE TITLE
repoConfig is not mounted into mofed container after upgrading to v24.1.0

### ISSUE THREAD

**Issue by age9990** [Mellanox/network-operator#845]
**What happened**: repoConfig is not mounted into mofed container after upgrading to v24.1.0

**What you expected to happen**: repoConfig is mounted into mofed container when repoConfig is set in values.yaml

**How to reproduce it (as minimally and precisely as possible)**: Every time deployed v24.1.0 with repoConfig set

**Anything else we need to know?**: Not encountered the issue in v23.7.0 & v23.10.0

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23
- Hardware configuration:
  - Network adapter model and firmware version:
- OS (e.g: `cat /etc/os-release`):Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.15.x
- Others:

**Comment by rollandf** [comment]
Thanks for reporting, @age9990 .
It is in fixed in #842 .
A minor release is planned to be released including this fix.

What is the scenario/setup that you use this feature? Which repositories do you include?

**Comment by age9990** [comment]
@rollandf Glad to hear that.
We need to reference an internally mirrored Ubuntu repository since our environment is air-gapped.
